host:
  name: spring-api-rest-test

server:
  port: ${server.port}
  create-time: 2019-08-08

# 出现错误时,直接抛出异常
spring:
  mvc:
    throw-exception-if-no-handler-found: true
#不要为我们工程中的资源文件建立映射
  resources:
      add-mappings: false