api:
  provider:
    name: "spring-api-provider"
server:
  port: 8910
spring:
  application:
    name: "spring-api-consumer"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring-api-provider:
  ribbon:
    listOfServers: http://localhost:8761